// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA95z0ka4IVqfot3difcGywT3mtNIZLAag',
    appId: '1:701605163143:web:2e1430f39e6871db538822',
    messagingSenderId: '701605163143',
    projectId: 'beaconguard-f325a',
    authDomain: 'beaconguard-f325a.firebaseapp.com',
    storageBucket: 'beaconguard-f325a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsgfJVfcAV0jtJfv6pGA4rEqdlaVhN4JA',
    appId: '1:701605163143:android:40e3e392489e3a01538822',
    messagingSenderId: '701605163143',
    projectId: 'beaconguard-f325a',
    storageBucket: 'beaconguard-f325a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeWb1BAr0xVyV8PfrB7upl3ebUAVO8OqU',
    appId: '1:701605163143:ios:a719034b21f80862538822',
    messagingSenderId: '701605163143',
    projectId: 'beaconguard-f325a',
    storageBucket: 'beaconguard-f325a.appspot.com',
    iosBundleId: 'com.example.hciProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeWb1BAr0xVyV8PfrB7upl3ebUAVO8OqU',
    appId: '1:701605163143:ios:a719034b21f80862538822',
    messagingSenderId: '701605163143',
    projectId: 'beaconguard-f325a',
    storageBucket: 'beaconguard-f325a.appspot.com',
    iosBundleId: 'com.example.hciProject',
  );
}
